### ISSUE TITLE
Check assignment - store service

### ISSUE THREAD

**Issue by AlekseiILitvinov** [AlekseiILitvinov/Week5HomeworkStoreService#1]
Я не уверен, что то, как я сделал постраничную выдачу, хорошо работает. Но, кажется, не падает, если целенаправленно не ронять.

**Comment by coursar** [comment]
Нужно, чтобы не падало совсем ))

**Comment by AlekseiILitvinov** [comment]
Try 2 - fixed issues to my best understanding
